image: continuumio/miniconda3:latest

before_script:
  - conda env create -f conda_env.yml
  - source activate simple_vslam_env

tests:
  stage: test
  script:
    - python -m unittest discover -s tests -v
