image: neufieldrobotics/conda_py3.5_gtsam

#before_script:
#  - source activate simple_vslam_env

stages:
  - test
  - deploy

test:
  stage: test
  timeout: 1 hours
  script:
  - python /gtsam_bin/cython/gtsam/examples/VisualISAMExample.py
  - python -m unittest discover -s tests -v
