language: minimal

services:
  - docker

matrix:
  include:
   - arch: amd64
     env : DOCKER_IMAGE=neufieldrobotics/conda_py3.5_gtsam:latest
   - arch: amd64
     env : DOCKER_IMAGE=neufieldrobotics/conda_py3.6_gtsam:gtsam_latest
   - arch: amd64
     env : DOCKER_IMAGE=neufieldrobotics/conda_py3.9_gtsam_4_1_1:latest
   - arch: amd64
     env : DOCKER_IMAGE=neufieldrobotics/conda_py3.9_gtsam_head:latest

before_install:
- docker pull $DOCKER_IMAGE

script:
- echo TRAVIS_BUILD_DIR is $TRAVIS_BUILD_DIR
- >
  docker run
  -v $TRAVIS_BUILD_DIR:/simple_vslam/
  $DOCKER_IMAGE
  /bin/bash -c 
  "
  echo $(pwd) &&
  echo "CONDA_PREFIX:" $CONDA_PREFIX &&
  conda env update -n py39_env --file conda_env.yml &&
  source activate py39_env &&
  echo "CONDA_PREFIX:" $CONDA_PREFIX &&
  python -m gtsam.examples.VisualISAM2Example &&
  cd simple_vslam &&
  tree -L 2 &&
  python temp_test_scripts/VisualISAM2withWrapper_Example.py &&
  yes | python temp_test_scripts/pnp_example_using_chessboard_points.py &&
  yes | python temp_test_scripts/recover_pose_test.py &&
  python temp_test_scripts/VisualISAM2withWrapper_Example.py &&
  yes | python ./vslam.py -c config/go_pro_Lab_800x600.yaml --quit &&
  python -m unittest discover -s tests -v
  "
