name: simple_vslam_env
channels:
  - defaults
dependencies:
  - python=3.5.6
  - opencv=3.3.1
  - matplotlib
  - numpy
  - scipy
  - pyyaml
  - colorama
  - progressbar2
  - pyqt
  - spyder-kernels
  - boost
  - cmake
  - pip
  - conda-build
  - pandas
  - spyder-kernels=0.*
  - conda-forge::exifread 
  - conda-forge::utm
  - cython
  - pyqt
  - pip
  - pyproj
  - cloudpickle
  - joblib
  - networkx
  - Pillow
  - pytest
  - python-dateutil
  - repoze.lru
  - six
  - xmltodict
  - sphinx
  - sphinx_rtd_theme
  - conda-forge::ceres-solver
  - conda-forge::gpxpy
  - conda-forge::sphinx-autobuild
  - conda-forge::exifread
