#K: 
#- [fx, 0, cx], 
#- [0, fy, cy], 
#- [0, 0, 1]])

K:
- [704.57264662,   0.0       , 403.39898405]
- [  0.0       , 682.12023168, 298.49026098]
- [  0.0       ,   0.0       ,   1.0       ]

D: 
- [-0.28272795, 0.1439448 , -0.00082586, 0.00006393, -0.0542582 ] #
#- [0.0, 0.0, 0.0, 0.0, 0.0]

#K:
#- [704.78050494,   0.0       , 403.64566634]
#- [  0.0       , 713.98436137, 294.65049908]
#- [  0.0       ,   0.0       ,   1.0       ]

#D: 
#- [-0.2813603 , 0.13800046, 0.00004876, -0.00006016, -0.04346666]

osx_image_folder: '/Users/vik748/Google Drive/data/Stingray2_080718_800x600'
linux_image_folder: '/home/vik748/data/Stingray2_080718_800x600'
#osx_image_folder: '/Users/vik748/Google Drive/data/Lars2_081018_800x600'
#linux_image_folder: '/Users/vik748/Google Drive/data/Lars2_081018_800x600'
#osx_image_folder: '/Users/vik748/Google Drive/data/Lars1_080818_800x600'
#linux_image_folder: '/home/vik748/data/Lars1_080818_800x600'
osx_ground_truth_poses: '/Users/vik748/Google Drive/data/Multibeam_pointcloud_correction/Stingray2_080718/position_output2_full_TFs.txt'
linux_ground_truth_poses: '/home/vik748/data/Multibeam_pointcloud_correction/Stingray2_080718/position_output2_full_TFs.txt'
image_ext: 'png'
chessboard: False
init_image_indxs: [420, 440]  #[1215, 1225] 
image_step: 5
use_masks: False
plot_landmarks: True
osx_masks_folder: '/Users/vik748/Google Drive/data/Stingray2_080718_800x600_masks_out'
linux_masks_folder: '/home/vik748/data/Stingray2_080718_800x600_masks_out'
masks_ext: 'png'
lowe_ratio_test_threshold: 0.9
use_RecoverPose_Filter: False
pause_every_iteration: True
use_gtsam: False

use_tiling_non_max_supression: False
tiling_non_max_tile_y: 17 
tiling_non_max_tile_x: 8 

radial_non_max: False
radial_non_max_radius: 5

use_clahe: False
CLAHE_settings:
 clipLimit: 10.0
 tileGridSize: !!python/tuple [8,6]

Triangulation_settings:
 z_threshold: 120 # In units set by frame 1 and 2
 subtended_angle_threshold: .01 # In degrees

findEssential_settings:
 prob: 0.9999
 threshold: 0.001

solvePnPRansac_settings:
  iterationsCount: 500
  reprojectionError: 0.003  # Using normalized coordinates, this is 1/width * (error in pixels) so 1/800 * 2 rounded to 0.003
  confidence: 0.9999

iSAM2_settings:
 pose0_to_pose1_range: 1.0
 relinearizeThreshold: 0.1
 relinearizeSkip: 10
 proj_noise_val: 0.00125  # 1/800

feature_detector_type: zernike
feature_descriptor_type: orb

ZERNIKE_settings:
 Nfeats: 1200
 seci: 4 
 secj: 3
 levels: 6
 ratio:  0.8333333333333334
 sigi: 2.75
 sigd: 1.0
 nmax: 8
 like_matlab: True
 lmax_nd: 3
 harris_threshold: 0.1

ORB_settings:
 WTA_K: 2
 edgeThreshold: 31
 patchSize: 31
 fastThreshold: 3
 firstLevel: 0
 nfeatures: 1200
 nlevels: 8
 scaleFactor: 1.2
 scoreType: 0

SURF_settings:
 hessianThreshold: 50
 nOctaves: 6

SIFT_settings:
 nfeatures: 1200
 nOctaveLayers: 3
 contrastThreshold: 0.01
 edgeThreshold: 20
 sigma: 1.6

#KLT_settings:
# criteria: !!python/tuple [3, 500, 0.001] #criteria = (cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT, 50, 0.03))
# maxLevel: 4
# winSize: !!python/tuple [15,15]
