osx_image_folder: '/Users/vik748/Google Drive/data/Stingray2_080718/'
osx_data_folder: '/Users/vik748/Google Drive/data/Metashape_Bundler_export/'
linux_image_folder: '/home/vik748/data/Stingray2_080718/'
linux_data_folder: '/home/vik748/data/Metashape_Bundler_export/'
data_pkl_file: 'Stingray2_08072018_metashape_pts_and_cams_local_coords_gs_150_15.pkl'
image_ext: 'JPG'

init_image_indxs: [15, 25]  #[1215, 1225] 
image_step: 5
use_masks: False
plot_landmarks: True
masks_ext: 'png'
use_RecoverPose_Filter: False
pause_every_iteration: True
use_gtsam: True
display_candidates: False

use_tiling_non_max_supression: False
tiling_non_max_tile_y: 17 
tiling_non_max_tile_x: 8 

radial_non_max: False
radial_non_max_radius: 5

Triangulation_settings:
 z_threshold: 60 # In units set by frame 1 and 2
 subtended_angle_threshold: .5 # In degrees

findEssential_settings:
 prob: 0.9999
 threshold: 0.001

solvePnPRansac_settings:
  iterationsCount: 250
  reprojectionError: 0.004  # Using normalized coordinates, this is 1/width * (error in pixels) so 1/4000 * 2 rounded to 0.0005
  confidence: 0.9999

iSAM2_settings:
# pose0_to_pose1_range: 1.0
 relinearizeThreshold: 0.1
 relinearizeSkip: 1
 proj_noise_val: 0.00003  # 1/376


