#K: 
#- [fx, 0, cx], 
#- [0, fy, cy], 
#- [0, 0, 1]])

K:
- [699.33112889, 0.0, 403.23876197]
- [0.0, 693.66457792, 293.40739086]
- [0.0, 0.0, 1.0]

D: 
- [-2.78089511e-01,  1.30037134e-01, -1.17555797e-04, -1.55337290e-04, -4.34486330e-02]

osx_image_folder: '/Users/vik748/Google Drive/data/time_lapse_5_cervino_800x600'
linux_image_folder: '/home/vik748/data/time_lapse_5_cervino_800x600'
image_ext: 'png'
chessboard: False
init_image_indxs: [1054, 1064] #[1204, 1214] [1054, 1064]
image_step: 2
use_masks: True
plot_landmarks: True
osx_masks_folder: '/Users/vik748/Google Drive/data/time_lapse_5_cervino_800x600_masks_out'
linux_masks_folder: '/home/vik748/data/time_lapse_5_cervino_800x600_masks_out'
masks_ext: 'png'
lowe_ratio_test_threshold: 0.85
use_RecoverPose_Filter: False

use_tiling_non_max_supression: False
tiling_non_max_tile_y: 17 
tiling_non_max_tile_x: 8 

radial_non_max: False
radial_non_max_radius: 5

use_clahe: False
CLAHE_settings:
 clipLimit: 10.0
 tileGridSize: !!python/tuple [8,6]

Triangulation_settings:
 z_threshold: 60 # In units set by frame 1 and 2
 subtended_angle_threshold: 0.25 # In degrees

findEssential_settings:
 prob: 0.9999
 threshold: 0.001

solvePnPRansac_settings:
  iterationsCount: 250
  reprojectionError: 0.004  # Using normalized coordinates, this is 1/width * (error in pixels) so 1/1241 * 2 rounded to 0.0009
  confidence: 0.9999

ZERNIKE_settings:
 Nfeats: 2400
 seci: 4 
 secj: 3
 levels: 6
 ratio: 0.75
 sigi: 2.75
 sigd: 1.0
 nmax: 8
 like_matlab: False
 lmax_nd: 3

iSAM2_settings:
 pose0_to_pose1_range: 1.0
 relinearizeThreshold: 0.1
 relinearizeSkip: 1
 proj_noise_val: 0.0017  # 1/376

ORB_settings:
 WTA_K: 2
 edgeThreshold: 31
 patchSize: 31
 fastThreshold: 5
 firstLevel: 0
 nfeatures: 10000
 nlevels: 8
 scaleFactor: 1.2
 scoreType: 0

KLT_settings:
 criteria: !!python/tuple [3, 500, 0.001] #criteria = (cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT, 50, 0.03))
 maxLevel: 4
 winSize: !!python/tuple [15,15]
