#K: 
#- [fx, 0, cx], 
#- [0, fy, cy], 
#- [0, 0, 1]])

K:
- [3502.75628, 0.0, 2019.97668]
- [0.0, 3477.0948, 1449.76175]
- [0.0, 0.0, 1.0]

D: 
- [-0.285711277, 0.16130412, 5.36070359e-05, -0.000148554708, -0.0771783829]

tiling_non_max_tile_y: 16 
tiling_non_max_tile_x: 12 
use_tiling_non_max_supression: True

radial_non_max: True
radial_non_max_radius: 5

image_folder: 'data/Lars2_081018'
image_ext: 'jpg'
chessboard: False
init_image_indxs: [165, 170]
image_step: 5
use_clahe: False
use_masks: True
masks_folder: 'data/Lars2_081018_clahe_masks2_out'
masks_ext: 'png'

ORB_settings:
 WTA_K: 2
 edgeThreshold: 125
 patchSize: 125
 fastThreshold: 5
 firstLevel: 0
 nfeatures: 10000
 nlevels: 8
 scaleFactor: 2.0
 scoreType: 0
