#K: 
#- [fx, 0, cx], 
#- [0, fy, cy], 
#- [0, 0, 1]])

# Calibration from Lars2_08102018_camera_calib_opencv_20200428.xml
K:
- [704.8071674690229, 0.0, 404.38567507076107]
- [0.0, 696.856518161123, 295.9523023199551]
- [0.0, 0.0, 1.0]

D: [-0.2855072360349615, 0.15825534100041033, -3.279847441885595e-05, -0.00017378382457899745,
  -0.07531545994327794]


osx_image_folder: '/Users/vik748/Google Drive/data/Lars2_081018_800x600'
linux_image_folder: '/home/vik748/data/Lars2_081018_800x600'
osx_ground_truth_poses: '/Users/vik748/Google Drive/data/Multibeam_pointcloud_correction/Lars2_081018/Lars_2_081018_camera_poses_mts_20200428.txt'
linux_ground_truth_poses: '/home/vik748/data/Multibeam_pointcloud_correction/Lars2_081018/Lars_2_081018_camera_poses_mts_20200428.txt'
image_ext: 'png'
init_image_indxs: [1100, 1115]
image_step: 10
use_masks: False
plot_landmarks: True
display_candidates: False
#osx_masks_folder: '/Users/vik748/Google Drive/data/Lars2_080818_800x600_masks_out'
#linux_masks_folder: '/home/vik748/data/Lars2_080818_800x600_masks_out'
masks_ext: 'png'
lowe_ratio_test_threshold: 0.90
use_RecoverPose_Filter: False
pause_every_iteration: True
use_gtsam: True
gtsam_interval: 1

use_tiling_non_max_supression: False
tiling_non_max_tile_y: 17 
tiling_non_max_tile_x: 8 

radial_non_max: False
radial_non_max_radius: 5

#pixel_matching_dist: 200

use_clahe: False
CLAHE_settings:
 clipLimit: 10.0
 tileGridSize: !!python/tuple [8,6]

Triangulation_settings:
 z_threshold: 300 # In units set by frame 1 and 2
 subtended_angle_threshold: .0005 # In degrees

findEssential_settings:
 prob: 0.9999
 threshold: 0.001

solvePnPRansac_settings:
  iterationsCount: 500
  reprojectionError: 0.003  # Using normalized coordinates, this is 1/width * (error in pixels) so 1/800 * 2 rounded to 0.003
  confidence: 0.9999

iSAM2_settings:
 #pose0_to_pose1_range: 1.0
 relinearizeThreshold: 0.1
 relinearizeSkip: 5
 proj_noise_val: 0.000125  # 1/800

feature_detector_type: zernike
feature_descriptor_type: zernike

ZERNIKE_settings:
 Nfeats: 1200
 seci: 4 
 secj: 3
 levels: 6
 ratio:  0.8334
 sigi: 2.75
 sigd: 1.0
 nmax: 8
 like_matlab: True
 lmax_nd: 3
 harris_threshold: 0.1

ORB_settings:
 WTA_K: 2
 edgeThreshold: 31
 patchSize: 31
 fastThreshold: 3
 firstLevel: 0
 nfeatures: 1200
 nlevels: 6
 scaleFactor: 1.2
 scoreType: 0

SURF_settings:
 hessianThreshold: 50
 nOctaves: 6

SIFT_settings:
 nfeatures: 1200
 nOctaveLayers: 3
 contrastThreshold: 0.01
 edgeThreshold: 20
 sigma: 1.6

#KLT_settings:
# criteria: !!python/tuple [3, 500, 0.001] #criteria = (cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT, 50, 0.03))
# maxLevel: 4
# winSize: !!python/tuple [15,15]
