#K: 
#- [fx, 0, cx], 
#- [0, fy, cy], 
#- [0, 0, 1]])

K:
- [524.888150200348832 ,   0.0               , 325.596989785447420 ]
- [  0.0               , 521.776791343664968 , 242.392342491041603 ]
- [  0.0               ,   0.0               ,   1.0        ]

D: 
- [-0.470302508060718438, 0.301057860458473880, 0.00468835914496582538, 0.00165573977268025185]

osx_image_folder: '/Users/vik748/Google Drive/data/ir_dataset_day_1'
linux_image_folder: '/home/vik748/data/ir_dataset_day_1'
#osx_ground_truth_poses: '/Users/vik748/Google Drive/data/Multibeam_pointcloud_correction/Stingray2_080718/position_output2_full_TFs.txt'
#linux_ground_truth_poses: '/home/vik748/data/Multibeam_pointcloud_correction/Stingray2_080718/position_output2_full_TFs.txt'
image_ext: 'jpg'
chessboard: False
init_image_indxs: [20, 40 ]
image_step: 10
use_masks: False
plot_landmarks: True
display_candidates: False
#osx_masks_folder: '/Users/vik748/Google Drive/data/Stingray2_080718_800x600_masks_out'
#linux_masks_folder: '/home/vik748/data/Stingray2_080718_800x600_masks_out'
#masks_ext: 'png'
lowe_ratio_test_threshold: 0.98
use_RecoverPose_Filter: False
pause_every_iteration: True
use_gtsam: True
gtsam_interval: 1

use_tiling_non_max_supression: False
tiling_non_max_tile_y: 17 
tiling_non_max_tile_x: 8 

radial_non_max: False
radial_non_max_radius: 5

use_clahe: False
CLAHE_settings:
 clipLimit: 10.0
 tileGridSize: !!python/tuple [8,6]

Triangulation_settings:
 z_threshold: 150 # In units set by frame 1 and 2
 subtended_angle_threshold: .005 # In degrees

findEssential_settings:
 prob: 0.999
 threshold: 0.001

solvePnPRansac_settings:
  iterationsCount: 500
  reprojectionError: 0.003  # Using normalized coordinates, this is 1/width * (error in pixels) so 1/800 * 2 rounded to 0.003
  confidence: 0.9999

iSAM2_settings:
 pose0_to_pose1_range: 1.0
 relinearizeThreshold: 0.1
 relinearizeSkip: 5
 proj_noise_val: 0.000125  # 1/800

feature_detector_type: orb
feature_descriptor_type: orb

ZERNIKE_settings:
 Nfeats: 12000
 seci: 5 
 secj: 4
 levels: 6
 ratio:  0.8334
 sigi: 2.75
 sigd: 1.0
 nmax: 8
 like_matlab: True
 lmax_nd: 3
# harris_threshold: None

ORB_settings:
 WTA_K: 2
 edgeThreshold: 15
 patchSize: 125
 fastThreshold: 5
 firstLevel: 0
 nfeatures: 25000
 nlevels: 32
 scaleFactor: 1.2
 scoreType: 0

SURF_settings:
 hessianThreshold: 50
 nOctaves: 6

SIFT_settings:
 nfeatures: 1200
 nOctaveLayers: 3
 contrastThreshold: 0.01
 edgeThreshold: 20
 sigma: 1.6

#KLT_settings:
# criteria: !!python/tuple [3, 500, 0.001] #criteria = (cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT, 50, 0.03))
# maxLevel: 4
# winSize: !!python/tuple [15,15]
