#K: 
#- [fx, 0, cx], 
#- [0, fy, cy], 
#- [0, 0, 1]])

K:
- [979.9200, 0.0, 690.0] 
- [0.0, 974.1183, 248.6443]
- [0.0, 0.0, 1.0]

#- [718.856, 0.0, 607.1928]
#- [0.0, 718.856, 185.2157]
#- [0.0, 0.0, 1.0]

D: 
- [-3.745594e-01, 2.049385e-01, 1.110145e-03, 1.379375e-03, -7.084798e-02]
#- [0.0, 0.0, 0.0, 0.0, 0.0]

tiling_non_max_tile_y: 17 
tiling_non_max_tile_x: 8 
use_tiling_non_max_supression: False

radial_non_max: False
radial_non_max_radius: 5

osx_image_folder: '/Users/vik748/Google Drive/data/kitti/image_00/data'
linux_image_folder: '/home/vik748/data/kitti/image_00/data'
image_ext: 'png'
chessboard: False
init_image_indxs: [1, 3]
image_step: 1
plot_landmarks: False
use_masks: False
use_clahe: False
lowe_ratio_test_threshold: 0.9

findEssential_settings:
 prob: 0.9999
 threshold: 0.01

CLAHE_settings:
 clipLimit: 10.0
 tileGridSize: !!python/tuple [8,6]

ZERNIKE_settings:
 Nfeats: 1200
 seci: 2 
 secj: 3
 levels: 6
 ratio: 0.75
 sigi: 2.75
 sigd: 1.0
 nmax: 8
 like_matlab: False
 lmax_nd: 3

ORB_settings:
 WTA_K: 4
 edgeThreshold: 31
 patchSize: 31
 fastThreshold: 5
 firstLevel: 0
 nfeatures: 10000
 nlevels: 8
 scaleFactor: 1.2
 scoreType: 0

KLT_settings:
 criteria: !!python/tuple [3, 50, 0.01] #criteria = (cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT, 50, 0.03))
 maxLevel: 4
 winSize: !!python/tuple [25,25]
