#K: 
#- [fx, 0, cx], 
#- [0, fy, cy], 
#- [0, 0, 1]])

K:
- [331.31, 0.0, 320]
- [0.0, 369.568, 240]
- [0.0, 0.0, 1.0]

D: 
- [0.0, 0.0, 0.0, 0.0, 0.0]

tiling_non_max_tile_y: 8 
tiling_non_max_tile_x: 6 
use_tiling_non_max_supression: True

radial_non_max: True
radial_non_max_radius: 5

image_folder: 'data/parking/images'
image_ext: 'png'
chessboard: False
init_image_indxs: [20, 22]
image_step: 2
use_masks: False
use_clahe: False

CLAHE_settings:
 clipLimit: 10.0
 tileGridSize: !!python/tuple [8,6]

ORB_settings:
 WTA_K: 4
 edgeThreshold: 31
 patchSize: 31
 fastThreshold: 10
 firstLevel: 0
 nfeatures: 2500
 nlevels: 8
 scaleFactor: 2.0
 scoreType: 0
 
KLT_settings:
 criteria: !!python/tuple [3, 50, 0.01] #criteria = (cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT, 50, 0.03))
 maxLevel: 4
 winSize: !!python/tuple [25,25]
