#K: 
#- [fx, 0, cx], 
#- [0, fy, cy], 
#- [0, 0, 1]])

K:
- [331.31, 0.0, 320]
- [0.0, 369.568, 240]
- [0.0, 0.0, 1.0]

D: 
- [0.0, 0.0, 0.0, 0.0, 0.0]

tiling_non_max_tile_y: 8 
tiling_non_max_tile_x: 6 
use_tiling_non_max_supression: False

radial_non_max: False
radial_non_max_radius: 5

image_folder: 'parking/images'
image_ext: 'png'
chessboard: False

ORB_settings:
 WTA_K: 4
 edgeThreshold: 31
 patchSize: 31
 fastThreshold: 10
 firstLevel: 0
 nfeatures: 2500
 nlevels: 8
 scaleFactor: 2.0
 scoreType: 0
